package ansi_test

import (
	"fmt"
	"github.com/tk-shirasaka/ansi"
)

func Example() {
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.BLACK, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GRAY, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.RED, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.RED, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_RED, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.GREEN, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_GREEN, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.YELLOW, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_YELLOW, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.BLUE, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_BLUE, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.MAGENTA, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_MAGENTA, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.CYAN, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_CYAN, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.LIGHT_WHITE, ansi.LIGHT_WHITE))
	fmt.Print("\n")

	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.BLACK))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.LIGHT_GRAY))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.RED))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.LIGHT_RED))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.GREEN))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.LIGHT_GREEN))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.YELLOW))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.LIGHT_YELLOW))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.BLUE))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.LIGHT_BLUE))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.MAGENTA))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.LIGHT_MAGENTA))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.CYAN))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.LIGHT_CYAN))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.WHITE))
	fmt.Print(ansi.Color("==", ansi.WHITE, ansi.LIGHT_WHITE))
}
